# Generated by Django 5.1.4 on 2024-12-12 17:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=2000)),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('example', models.TextField(blank=True, max_length=2000, null=True)),
                ('param', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.date.today)),
                ('creator_name', models.CharField(max_length=255)),
                ('creator_email', models.CharField(max_length=255)),
                ('creator_message', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='category.category')),
            ],
        ),
    ]
