# Generated by Django 5.2.7 on 2026-02-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='closing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='closing_de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='closing_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
