# Generated by Django 5.1.4 on 2025-03-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_de',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='command_en',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
