# Generated by Django 5.2.7 on 2025-12-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='alternatives',
            new_name='alternative',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='options',
            new_name='option',
        ),
    ]
