# Generated by Django 5.2.7 on 2026-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_command_closing_command_closing_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='closing',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='closing_de',
            new_name='context_de',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='closing_en',
            new_name='context_en',
        ),
        migrations.AddField(
            model_name='command',
            name='context_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='context_description_de',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='context_description_en',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
