# Generated by Django 5.1.4 on 2024-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_alter_command_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='param',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
