# Generated by Django 5.2.7 on 2026-02-28 08:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_rename_closing_command_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='example',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, default=list, size=None),
        ),
    ]
