# Generated by Django 5.1.4 on 2025-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0003_alter_command_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='creator_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
