# Generated by Django 5.1.4 on 2025-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_alter_command_creator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='tooltip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
