# Generated by Django 5.2.7 on 2026-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_alter_command_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='alternative_override_option',
            field=models.BooleanField(default=True),
        ),
    ]
