# Generated by Django 5.2.7 on 2026-03-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_command_alternative_override_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='alternative_override_option',
        ),
    ]
