# Generated by Django 5.2.7 on 2026-03-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_remove_command_alternative_override_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='title',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='command',
            name='title_de',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='title_en',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
