# Generated by Django 5.1.4 on 2025-01-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_alter_category_description_and_more'),
        ('command', '0006_command_copycount_alter_command_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command', to='category.subcategory'),
        ),
    ]
