# Generated by Django 5.2.7 on 2026-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0007_alter_command_title_alter_command_title_de_and_more'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='commands', to='tag.tag'),
        ),
    ]
