# Generated by Django 5.1.4 on 2025-01-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0007_alter_command_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='param',
        ),
    ]
