# Generated by Django 5.1.4 on 2025-01-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_remove_command_param'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='copyCount',
            new_name='copy_count',
        ),
    ]
