# Generated by Django 5.2.7 on 2026-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_command_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='equivalent',
            field=models.ManyToManyField(blank=True, related_name='equivalent_to', to='command.command'),
        ),
    ]
