# Generated by Django 5.2.7 on 2026-05-10 10:09

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('command', '0009_command_equivalent'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='command',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='cmd_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='command',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='cmd_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
