# Generated by Django 5.1.4 on 2025-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0009_rename_copycount_command_copy_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='copy_count',
            field=models.IntegerField(default=0),
        ),
    ]
