# Generated by Django 5.2.7 on 2026-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_ca_active_eefb18_idx'),
        ('command', '0010_command_cmd_title_trgm_command_cmd_desc_trgm'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['active'], name='command_com_active_6cedff_idx'),
        ),
    ]
