# Generated by Django 5.1.4 on 2025-01-17 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('routine', models.CharField(max_length=30000)),
                ('example', models.CharField(blank=True, max_length=2000, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=1000, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creator_email', models.CharField(blank=True, max_length=255, null=True)),
                ('creator_message', models.CharField(blank=True, max_length=10000, null=True)),
                ('copy_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='category.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='category.subcategory')),
            ],
        ),
    ]
