# Generated by Django 5.2.7 on 2025-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_de', models.CharField(max_length=255, null=True, unique=True)),
                ('routine', models.TextField(blank=True, null=True)),
                ('routine_en', models.TextField(blank=True, null=True)),
                ('routine_de', models.TextField(blank=True, null=True)),
                ('example', models.CharField(blank=True, max_length=2000, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=1000, null=True)),
                ('tooltip_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('tooltip_de', models.CharField(blank=True, max_length=1000, null=True)),
                ('copy_count', models.IntegerField(default=0)),
                ('alternatives', models.ManyToManyField(blank=True, related_name='alternative_to', to='routine.routine')),
                ('category', models.ManyToManyField(related_name='routines', to='category.category')),
            ],
        ),
    ]
