# Generated by Django 5.0.6 on 2025-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine',
            field=models.TextField(),
        ),
    ]
