# Generated by Django 5.2.7 on 2025-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('description_de', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
