# Generated by Django 5.2.7 on 2026-01-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
