# Generated by Django 5.2.7 on 2026-02-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_alter_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='value_de',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='value_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
