# Generated by Django 5.2.7 on 2026-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_option_value_de_option_value_en_alter_option_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='description_de',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='description_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
