# Generated by Django 5.2.7 on 2026-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0004_alter_option_description_alter_option_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='standalone',
            field=models.BooleanField(default=False),
        ),
    ]
