# Generated by Django 5.2.7 on 2026-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0005_option_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
