# Generated by Django 5.2.7 on 2026-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_option_title_de_option_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='overwrite',
            field=models.BooleanField(default=False),
        ),
    ]
