# Generated by Django 5.2.7 on 2026-03-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0007_option_overwrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='value',
        ),
        migrations.RemoveField(
            model_name='option',
            name='value_de',
        ),
        migrations.RemoveField(
            model_name='option',
            name='value_en',
        ),
    ]
