# Generated by Django 5.2.7 on 2026-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('option', '0008_remove_option_value_remove_option_value_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
