# Generated by Django 5.2.7 on 2026-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_ca_active_eefb18_idx'),
        ('command', '0011_command_command_com_active_6cedff_idx'),
        ('option', '0009_option_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['active'], name='option_opti_active_b1cc33_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['command', 'active'], name='option_opti_command_c3d7bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('command', 'title'), name='uniq_option_command_title'),
        ),
    ]
