# Generated by Django 5.2.7 on 2025-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('title_en', models.CharField(max_length=40, null=True, unique=True)),
                ('title_de', models.CharField(max_length=40, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('description_de', models.TextField(blank=True, max_length=10000, null=True)),
                ('type', models.CharField(choices=[('command', 'Command'), ('routine', 'Routine'), ('function', 'Function')], default='command', max_length=10)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
