# Generated by Django 5.1.4 on 2024-12-12 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
