# Generated by Django 5.2.7 on 2026-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['active'], name='category_ca_active_eefb18_idx'),
        ),
    ]
