# Generated by Django 5.2.7 on 2026-06-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_ca_active_eefb18_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'active'], name='category_ca_type_bfb6bd_idx'),
        ),
    ]
