# Generated by Django 5.1.4 on 2025-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('command', 'Command'), ('routine', 'Routine'), ('function', 'Function')], default='command', max_length=10),
        ),
    ]
